# Generated by Django 4.2.2 on 2023-07-02 23:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id_evento', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_evento', models.CharField(max_length=255)),
                ('descripcion_evento', models.TextField()),
                ('fecha_evento', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_finalizacion', models.TimeField()),
                ('fecha_finalizacion', models.DateField()),
                ('capacidad_total', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Seccion',
            fields=[
                ('id_seccion', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_seccion', models.CharField(max_length=255)),
                ('capacidad_seccion', models.IntegerField()),
                ('precio_asiento', models.DecimalField(decimal_places=2, max_digits=10)),
                ('id_evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.evento')),
            ],
        ),
    ]
